source 'https://rubygems.org'
gem 'jekyll-paginate'
gem "jekyll", "~> 4.0"
gem "rake"

gem "webrick", "~> 1.7"

gem 'jekyll-minibundle'

# gem "jekyll-minibundle", "~> 3.0" 

# gem "jekyll-minibundle", "~> 3.0"
